// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.panzyma.nm.serviceproxy;

public class CVenta {
    protected java.lang.String NumeroCentral;
    protected java.lang.String NombreCliente;
    protected java.lang.String Fecha;
    protected float Total;
    protected java.lang.String NumeroMovil;
    
    public CVenta() {
    }
    
    public CVenta(java.lang.String numeroCentral, java.lang.String nombreCliente, java.lang.String fecha, float total, java.lang.String numeroMovil) {
        this.NumeroCentral = numeroCentral;
        this.NombreCliente = nombreCliente;
        this.Fecha = fecha;
        this.Total = total;
        this.NumeroMovil = numeroMovil;
    }
    
    public java.lang.String getNumeroCentral() {
        return NumeroCentral;
    }
    
    public void setNumeroCentral(java.lang.String numeroCentral) {
        this.NumeroCentral = numeroCentral;
    }
    
    public java.lang.String getNombreCliente() {
        return NombreCliente;
    }
    
    public void setNombreCliente(java.lang.String nombreCliente) {
        this.NombreCliente = nombreCliente;
    }
    
    public java.lang.String getFecha() {
        return Fecha;
    }
    
    public void setFecha(java.lang.String fecha) {
        this.Fecha = fecha;
    }
    
    public float getTotal() {
        return Total;
    }
    
    public void setTotal(float total) {
        this.Total = total;
    }
    
    public java.lang.String getNumeroMovil() {
        return NumeroMovil;
    }
    
    public void setNumeroMovil(java.lang.String numeroMovil) {
        this.NumeroMovil = numeroMovil;
    }
}
