// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.panzyma.nm.serviceproxy;

public class CVenta {
    protected java.lang.String numeroCentral;
    protected java.lang.String nombreCliente;
    protected java.lang.String fecha;
    protected float total;
    protected java.lang.String numeroMovil;
    
    public CVenta() {
    }
    
    public CVenta(java.lang.String numeroCentral, java.lang.String nombreCliente, java.lang.String fecha, float total, java.lang.String numeroMovil) {
        this.numeroCentral = numeroCentral;
        this.nombreCliente = nombreCliente;
        this.fecha = fecha;
        this.total = total;
        this.numeroMovil = numeroMovil;
    }
    
    public java.lang.String getNumeroCentral() {
        return numeroCentral;
    }
    
    public void setNumeroCentral(java.lang.String numeroCentral) {
        this.numeroCentral = numeroCentral;
    }
    
    public java.lang.String getNombreCliente() {
        return nombreCliente;
    }
    
    public void setNombreCliente(java.lang.String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    
    public java.lang.String getFecha() {
        return fecha;
    }
    
    public void setFecha(java.lang.String fecha) {
        this.fecha = fecha;
    }
    
    public float getTotal() {
        return total;
    }
    
    public void setTotal(float total) {
        this.total = total;
    }
    
    public java.lang.String getNumeroMovil() {
        return numeroMovil;
    }
    
    public void setNumeroMovil(java.lang.String numeroMovil) {
        this.numeroMovil = numeroMovil;
    }
}
