// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.panzyma.nm.serviceproxy;

import java.util.Hashtable;

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;

import android.os.Parcel;
import android.os.Parcelable;

public class ReciboDetFormaPago implements KvmSerializable, Parcelable {
	protected long Id;
	protected long ObjReciboID;
	protected long ObjFormaPagoID;
	protected java.lang.String CodFormaPago;
	protected java.lang.String DescFormaPago;
	protected java.lang.String Numero;
	protected long ObjMonedaID;
	protected java.lang.String CodMoneda;
	protected java.lang.String DescMoneda;
	protected float Monto;
	protected float MontoNacional;
	protected long ObjEntidadID;
	protected java.lang.String CodEntidad;
	protected java.lang.String DescEntidad;
	protected int Fecha;
	protected java.lang.String SerieBilletes;
	protected float TasaCambio;

	public ReciboDetFormaPago() {
	}

	public ReciboDetFormaPago(long id, long objFormaPagoID,
			java.lang.String codFormaPago, java.lang.String descFormaPago,
			java.lang.String numero, long objMonedaID,
			java.lang.String codMoneda, java.lang.String descMoneda,
			float monto, float montoNacional, long objEntidadID,
			java.lang.String codEntidad, java.lang.String descEntidad,
			int fecha, java.lang.String serieBilletes, float tasaCambio) {
		this.Id = id;
		this.ObjFormaPagoID = objFormaPagoID;
		this.CodFormaPago = codFormaPago;
		this.DescFormaPago = descFormaPago;
		this.Numero = numero;
		this.ObjMonedaID = objMonedaID;
		this.CodMoneda = codMoneda;
		this.DescMoneda = descMoneda;
		this.Monto = monto;
		this.MontoNacional = montoNacional;
		this.ObjEntidadID = objEntidadID;
		this.CodEntidad = codEntidad;
		this.DescEntidad = descEntidad;
		this.Fecha = fecha;
		this.SerieBilletes = serieBilletes;
		this.TasaCambio = tasaCambio;
	}

	public ReciboDetFormaPago(Parcel parcel) {
		// TODO Auto-generated constructor stub
		readFromParcel(parcel);
	}

	public long getId() {
		return Id;
	}

	public void setId(long id) {
		this.Id = id;
	}

	public long getObjFormaPagoID() {
		return ObjFormaPagoID;
	}

	public void setObjFormaPagoID(long objFormaPagoID) {
		this.ObjFormaPagoID = objFormaPagoID;
	}

	public java.lang.String getCodFormaPago() {
		return CodFormaPago;
	}

	public void setCodFormaPago(java.lang.String codFormaPago) {
		this.CodFormaPago = codFormaPago;
	}

	public java.lang.String getDescFormaPago() {
		return DescFormaPago;
	}

	public void setDescFormaPago(java.lang.String descFormaPago) {
		this.DescFormaPago = descFormaPago;
	}

	public java.lang.String getNumero() {
		return Numero;
	}

	public void setNumero(java.lang.String numero) {
		this.Numero = numero;
	}

	public long getObjMonedaID() {
		return ObjMonedaID;
	}

	public void setObjMonedaID(long objMonedaID) {
		this.ObjMonedaID = objMonedaID;
	}

	public java.lang.String getCodMoneda() {
		return CodMoneda;
	}

	public void setCodMoneda(java.lang.String codMoneda) {
		this.CodMoneda = codMoneda;
	}

	public java.lang.String getDescMoneda() {
		return DescMoneda;
	}

	public void setDescMoneda(java.lang.String descMoneda) {
		this.DescMoneda = descMoneda;
	}

	public float getMonto() {
		return Monto;
	}

	public void setMonto(float monto) {
		this.Monto = monto;
	}

	public float getMontoNacional() {
		return MontoNacional;
	}

	public void setMontoNacional(float montoNacional) {
		this.MontoNacional = montoNacional;
	}

	public long getObjEntidadID() {
		return ObjEntidadID;
	}

	public void setObjEntidadID(long objEntidadID) {
		this.ObjEntidadID = objEntidadID;
	}

	public java.lang.String getCodEntidad() {
		return CodEntidad;
	}

	public void setCodEntidad(java.lang.String codEntidad) {
		this.CodEntidad = codEntidad;
	}

	public java.lang.String getDescEntidad() {
		return DescEntidad;
	}

	public void setDescEntidad(java.lang.String descEntidad) {
		this.DescEntidad = descEntidad;
	}

	public int getFecha() {
		return Fecha;
	}

	public void setFecha(int fecha) {
		this.Fecha = fecha;
	}

	public java.lang.String getSerieBilletes() {
		return SerieBilletes;
	}

	public void setSerieBilletes(java.lang.String serieBilletes) {
		this.SerieBilletes = serieBilletes;
	}

	public float getTasaCambio() {
		return TasaCambio;
	}

	public void setTasaCambio(float tasaCambio) {
		this.TasaCambio = tasaCambio;
	}

	@Override
	public Object getProperty(int _index) {
		switch (_index) {
		case 0:
			return new Long(Id);
		case 1:
			return new Long(ObjFormaPagoID);
		case 2:
			return CodFormaPago;
		case 3:
			return DescFormaPago;
		case 4:
			return Numero;
		case 5:
			return new Long(ObjMonedaID);
		case 6:
			return CodMoneda;
		case 7:
			return DescMoneda;
		case 8:
			return Monto;
		case 9:
			return MontoNacional;
		case 10:
			return new Long(ObjEntidadID);
		case 11:
			return CodEntidad;
		case 12:
			return DescEntidad;
		case 13:
			return new Integer(Fecha);
		case 14:
			return SerieBilletes;
		case 15:
			return TasaCambio;
		}
		return null;
	}

	@Override
	public int getPropertyCount() {
		// TODO Auto-generated method stub
		return 16;
	}

	@Override
	public void getPropertyInfo(int _index, Hashtable _table, PropertyInfo _info) {
		switch (_index) {
		case 0:
			_info.name = "Id";
			_info.type = Long.class;
			break;
		case 1:
			_info.name = "ObjFormaPagoID";
			_info.type = Long.class;
			break;
		case 2:
			_info.name = "CodFormaPago";
			_info.type = String.class;
			break;
		case 3:
			_info.name = "DescFormaPago";
			_info.type = String.class;
			break;
		case 4:
			_info.name = "Numero";
			_info.type = String.class;
			break;
		case 5:
			_info.name = "ObjMonedaID";
			_info.type = Long.class;
			break;
		case 6:
			_info.name = "CodMoneda";
			_info.type = String.class;
			break;
		case 7:
			_info.name = "DescMoneda";
			_info.type = String.class;
			break;
		case 8:
			_info.name = "Monto";
			_info.type = Float.class;
			break;
		case 9:
			_info.name = "MontoNacional";
			_info.type = Float.class;
			break;
		case 10:
			_info.name = "ObjEntidadID";
			_info.type = Long.class;
			break;
		case 11:
			_info.name = "CodEntidad";
			_info.type = String.class;
			break;
		case 12:
			_info.name = "DescEntidad";
			_info.type = String.class;
			break;
		case 13:
			_info.name = "Fecha";
			_info.type = Integer.class;
			break;
		case 14:
			_info.name = "SerieBilletes";
			_info.type = String.class;
			break;
		case 15:
			_info.name = "TasaCambio";
			_info.type = Float.class;
			break;
		}

	}

	@Override
	public void setProperty(int _index, Object _obj) {
		switch (_index) {
		case 0:
			Id = Long.parseLong(_obj.toString());
			break;
		case 1:
			ObjFormaPagoID = Long.parseLong(_obj.toString());
			break;
		case 2:
			CodFormaPago = (_obj.toString());
			break;
		case 3:
			DescFormaPago = (_obj.toString());
			break;
		case 4:
			Numero = (_obj.toString());
			break;
		case 5:
			ObjMonedaID = Long.parseLong(_obj.toString());
			break;
		case 6:
			CodMoneda = (_obj.toString());
			break;
		case 7:
			DescMoneda = (_obj.toString());
			break;
		case 8:
			Monto = Float.valueOf(_obj.toString());
			break;
		case 9:
			MontoNacional = Float.valueOf(_obj.toString());
			break;
		case 10:
			ObjEntidadID = Long.parseLong(_obj.toString());
			break;
		case 11:
			CodEntidad = (_obj.toString());
			break;
		case 12:
			DescEntidad = (_obj.toString());
			break;
		case 13:
			Fecha = Integer.valueOf(_obj.toString());
			break;
		case 14:
			SerieBilletes = (_obj.toString());
			break;
		case 15:
			TasaCambio = Float.valueOf(_obj.toString());
			break;
		}

	}

	public static final Parcelable.Creator CREATOR = new Parcelable.Creator() {
		public ReciboDetFormaPago createFromParcel(Parcel parcel) {
			return new ReciboDetFormaPago(parcel);
		}

		public ReciboDetFormaPago[] newArray(int size) {
			return new ReciboDetFormaPago[size];
		}

	};

	@Override
	public int describeContents() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void writeToParcel(Parcel parcel, int flags) {
		// TODO Auto-generated method stub
		parcel.writeLong(Id);
		parcel.writeLong(ObjFormaPagoID);
		parcel.writeString(CodFormaPago);
		parcel.writeString(DescFormaPago);
		parcel.writeString(Numero);
		parcel.writeLong(ObjMonedaID);
		parcel.writeString(CodMoneda);
		parcel.writeString(DescMoneda);
		parcel.writeFloat(Monto);
		parcel.writeFloat(MontoNacional);
		parcel.writeLong(ObjEntidadID);
		parcel.writeString(CodEntidad);
		parcel.writeString(DescEntidad);
		parcel.writeInt(Fecha);
		parcel.writeString(SerieBilletes);
		parcel.writeFloat(TasaCambio);
	}

	private void readFromParcel(Parcel parcel) {
		this.Id = parcel.readLong();
		this.ObjFormaPagoID = parcel.readLong();
		this.CodFormaPago = parcel.readString();
		this.DescFormaPago = parcel.readString();
		this.Numero = parcel.readString();
		this.ObjMonedaID = parcel.readLong();
		this.CodMoneda = parcel.readString();
		this.DescMoneda = parcel.readString();
		this.Monto = parcel.readFloat();
		this.MontoNacional = parcel.readFloat();
		this.ObjEntidadID = parcel.readLong();
		this.CodEntidad = parcel.readString();
		this.DescEntidad = parcel.readString();
		this.Fecha = parcel.readInt();
		this.SerieBilletes = parcel.readString();
		this.TasaCambio = parcel.readFloat();
	}

	public long getObjReciboID() {
		return ObjReciboID;
	}

	public void setObjReciboID(long objReciboID) {
		ObjReciboID = objReciboID;
	}

}
