package com.panzyma.nm.serviceproxy;

//This class was generated by the JAXRPC SI, do not edit.
//Contents subject to change without notice.
//JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)
 
public class RespuestaEnviarRecibo {
 protected ValorCatalogo nuevoEstado;
 protected int numeroCentral;
 
 public RespuestaEnviarRecibo() {
 }
 
 public RespuestaEnviarRecibo(ValorCatalogo nuevoEstado, int numeroCentral) {
     this.nuevoEstado = nuevoEstado;
     this.numeroCentral = numeroCentral;
 }
 
 public ValorCatalogo getNuevoEstado() {
     return nuevoEstado;
 }
 
 public void setNuevoEstado(ValorCatalogo nuevoEstado) {
     this.nuevoEstado = nuevoEstado;
 }
 
 public int getNumeroCentral() {
     return numeroCentral;
 }
 
 public void setNumeroCentral(int numeroCentral) {
     this.numeroCentral = numeroCentral;
 }
}

